linters:
  enable-all: true
  disable:
    - containedctx
    - dupl
    - funlen
    - gci
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - godox
    - goerr113
    - gomnd
    - ifshort
    - ireturn
    - lll
    - nestif
    - nlreturn
    - paralleltest
    - prealloc
    - scopelint
    - testpackage
    - tparallel
    - unparam
    - varnamelen
    - wrapcheck
    - wsl

    # deplicated
    - exhaustivestruct
    - golint
    - interfacer
    - maligned
    - scopelint

    # TODO: v1.0.4 works correctly, but golangci-lint bundles v1.0.1.
    - nonamedreturns

  skip-dirs:
    - gen

issues:
  exclude-rules:
    - path: _test.go
      linters:
        - exhaustruct
        - forcetypeassert
        - goconst
        - noctx

linters-settings:
  exhaustive:
    default-signifies-exhaustive: true
  exhaustruct:
    exclude:
    - 'cobra\.Command$'
    - 'http\.Client$'
    - 'http\.Server$'
    - 'xml\.Name$'
    - 'github\.com/zoncoen/scenarigo/errors\.MultiPathError$'
    - 'github\.com/zoncoen/scenarigo/errors\.PathError$'
    - 'github\.com/zoncoen/scenarigo/internal/testutil\.reporter$'
    - 'github\.com/zoncoen/scenarigo/mock/protocol/http\.server$'
    - 'github\.com/zoncoen/scenarigo/reporter\..+Report$'
    - 'github\.com/zoncoen/scenarigo/reporter\.[a-z].+$'
    - 'github\.com/zoncoen/scenarigo/template/ast\..+$'
    - 'github\.com/zoncoen/scenarigo/template/parser\..+$'
    - 'github\.com/zoncoen/scenarigo/template\.Template$'
  stylecheck:
    checks:
    - all
    # revive has same rules
    - -ST1005
    - -ST1006
