linters:
  enable-all: true
  disable:
    - containedctx
    - dupl
    - funlen
    - gci
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - godox
    - goerr113
    - gomnd
    - ifshort
    - ireturn
    - lll
    - nestif
    - nlreturn
    - prealloc
    - scopelint
    - testpackage
    - unparam
    - varnamelen
    - wrapcheck
    - wsl

    # deplicated
    - exhaustivestruct
    - golint
    - interfacer
    - maligned
    - scopelint

    # TODO: v1.0.4 works correctly, but golangci-lint bundles v1.0.1.
    - nonamedreturns

  skip-dirs:
    - gen

issues:
  exclude-rules:
    - path: _test.go
      linters:
        - goconst
        - noctx
    - linters:
        - stylecheck
      text: "ST1016:"

linters-settings:
  exhaustive:
    default-signifies-exhaustive: true
