before:
  hooks:
  - go mod download
builds:
- main: ./cmd/scenarigo
  ldflags:
  - -s -w
  - -X github.com/zoncoen/scenarigo/version.version={{.Version}}
  - -X github.com/zoncoen/scenarigo/version.revision=
  env:
  - CGO_ENABLED=0
archives:
- name_template: "{{ .ProjectName  }}_v{{ .Version }}_{{ .Os  }}_{{ .Arch  }}"
  replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
  format_overrides:
  - goos: windows
    format: zip
  files:
  - README.md
  - CHANGELOG.md
  - LICENSE
  - CREDITS
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Version }}-next"
changelog:
  skip: true
