name: generate CREDITS
on:
  pull_request_target:
    branches:
    - 'dependabot/**'
jobs:
  generate:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    steps:
    - name: Install Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19.x
    - name: Generate token # required to trigger actions on the commit
      id: generate_token
      uses: tibdex/github-app-token@v1.6.0
      with:
        app_id: ${{ secrets.WRITE_APP_ID }}
        private_key: ${{ secrets.WRITE_PRIVATE_KEY }}
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.sha  }}
        token: ${{ steps.generate_token.outputs.token }}
    - name: Generate CREDITS
      run: make credits
    - uses: EndBug/add-and-commit@v9
      with:
        add: CREDITS
        default_author: github_actions
        message: 'chore(deps): generate CREDITS'
