name: release
on:
  push:
    tags:
    - "v[0-9]+.[0-9]+.[0-9]+"
jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v2.1.3
      with:
        go-version: 1.16
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        path: go/src/github.com/${{ github.repository }}
    - name: Generate CHANGELOG
      working-directory: ./go/src/github.com/${{ github.repository }}
      run: make changelog/ci && cat .CHANGELOG.md
    - name: Build
      working-directory: ./go/src/github.com/${{ github.repository }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: make build/ci
    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v2
      with:
        version: latest
        args: release --rm-dist --release-notes .CHANGELOG.md
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
