model:
  filename: ./gen/models_gen.go
client:
  filename: ./gen/client.go
models:
  DateTime:
    model: github.com/99designs/gqlgen/graphql.Time
endpoint:
  url: https://api.github.com/graphql
  headers:
    Authorization: "Bearer ${GITHUB_TOKEN}"
query:
  - "./query/*.graphql"
generate:
  clientV2: true
  clientInterfaceName: "GithubGraphQLClient"
